# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build-energy-cli

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Config Base Environment  # 配置基础环境
      run: |
        mkdir D:/clis
      shell: bash

    - name: Build CLI
      run: |
        cd ./cmd/energy/md5
        go install
        cd ../
        ./build.bat
        ./compress-zip.bat
        
        mv energy-windows32.zip D:/clis
        mv energy-windows64.zip D:/clis
        mv energy-macosx64.zip D:/clis
        mv energy-macosarm64.zip D:/clis
        mv energy-linux32.zip D:/clis
        mv energy-linux64.zip D:/clis
        mv energy-linuxarm.zip D:/clis
        mv energy-linuxarm64.zip D:/clis
      shell: bash

    - name: Build CLI END
      run: |
        ls -l D:/clis
      shell: bash