name: Release Version

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    tags:
#      - 'v*.*.*'

jobs:
  windows-64:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build CLI
        run: |
          cd ./cmd/energy/md5
          go install
          cd ../
          ./build.bat
          ./compress-zip.bat
          ls
          pwd
        shell: bash

      - name: Release CLI
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ../bins/**


